### ISSUE TITLE
안녕하세요. 조금 아쉬운점이 있네요.

### ISSUE THREAD

**Issue by proplcy** [kimyearho/WebtoonDownloadManager#16]
wdm fx v0.5 버전입니다. 사소할 수 있는 문제이지만 예약리스트를 활용하기 위해서 여러개의 웹툰을 받게 되는데 이때 웹툰선택창에서 웹툰을 선택하고 창이 꺼집니다. 이 창이 안꺼지면 여러개 추가하기가 편할거 같습니다. 

그리고.. 이전 / 다음 버튼...추가가 힘들려나요 ㅎㅎ 소개해주신 http://www.cdisplayex.com은 윈도우버전만 있어서...주로 패드로 보는 저는 좀 아쉽네요. 그래서 구버전인 1.41로 나중에 편하게 볼려고 따로 받아놨네요. 
안드로이드나 아이패드 쪽에서 마땅한 웹툰 뷰어를 못찾겠네요 ㅠㅠ

그래도 항상 감사하게 쓰고 있습니다!

**Comment by kimyearho** [comment]
안녕하세요. proplcy님.
말씀하신 예약 리스트를 활용하기 위해 웹툰 선택창에서 웹툰을 선택하고 닫히면서 불편함을
지적 해주셨는데, 좋은 지적인것 같습니다. wdmFX가 현재 주요 기능 개발이 종료된 시점이라, 
더이상 추가 개발을 하지 않고 있습니다만, 지적 해주신 부분은 분명 필요해 보입니다.
따라서 해당 부분은 이번주 이내로 업데이트 하겠습니다.

그리고 이전/다음 버튼을 제기 해주셨는데, 이 기능을 여전히 필요로 하시는분이 계시네요.
음.. 알겠습니다. 해당 기능 버킷 리스트에 올려놓겠습니다. 
말씀 드린대로 wdmFX는 현재 개발이 종료된 상태입니다. 신규기능은 다소 지양하고 있습니다.
따라서 위 기능보다는 다소 늦어질 수도 있고, 같이 될 수도 있습니다. 이건 아무래도 제 직업의 업무일정에 따라 조금 차이가 생길 수 있는 부분입니다. 이 부분 다소 감안해 주신다면 조속히 업데이트 될 수 있도
록 노력하겠습니다.

항상 wdmFX 를 사용해 주셔서 감사드리고, 피드백 언제나 환영합니다.
감사합니다. 항상 행복하세요.

**Comment by proplcy** [comment]
사용자로서는 이런 프로그램을 만들어주신것만 해도 항상 감사할 따름입니다. 저도 이런거 한번 만들어보고 싶어서 문과지만 파이썬 책사서 조금씩 보고있네요. 프로그램을 만들지는 못하겠지만요.ㅎㅎ
많이 늦어도 기다릴태니 생업에 지장없게 하셨으면 좋겠습니다!

**Comment by kimyearho** [comment]
파이썬 배우기 쉽고, 강력한 언어입니다. 추천 드립니다.
프로그래밍 입문에 문과/이과 중요하지 않습니다. 
프로그래밍은 하고자 하는 의지만 있으면 누구나 할 수 있는 영역 입니다.

응원합니다.

**Comment by proplcy** [comment]
응원 감사합니다. 좋은 하루 보내세요~

**Comment by kimyearho** [comment]
예약 리스트 팝업창 닫히는 문제는 변경하여 업데이트 되었습니다.
앱을 종료 후 새로 업데이트 받아주시길 바랍니다.

감사합니다.
